server:
  port: ${SERVER_PORT:8080} # Используем переменную из docker-compose, с fallback'ом

spring:
  datasource:
    # Эти значения будут заменены переменными окружения из docker-compose.yml
    # Нет необходимости жестко прописывать их здесь.
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update # или validate в зависимости от вашей стратегии
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true # Полезно для разработки
  profiles:
    active: local 